openapi: 3.0.3
info:
  title: PetSitter API
  version: "0.1"
tags:
  - name: Users
    description: User-related operations
  - name: Jobs
    description: Job-related operations
paths:
  /users:
    post:
      tags:
      - Users
      summary: Register User
      operationId: registerUser
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      security: []
  /users/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      tags:
      - Users
      summary: View User
      operationId: viewUserWithId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags:
      - Users
      summary: Modify User
      operationId: modifyUserWithId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutUserRequest'
    delete:
      tags:
      - Users
      summary: Delete User
      operationId: deleteUserWithId
      responses:
        '204':
          description: No Content
  /jobs:
    post:
      tags:
      - Jobs
      summary: Create Job
      operationId: createJob
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostJobRequest'
    get:
      tags:
      - Jobs
      summary: List All Jobs
      operationId: listAllJobs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Job'
  /jobs/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      tags:
      - Jobs
      summary: View Job
      operationId: viewJobWithId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
    put:
      tags:
      - Jobs
      summary: Modify Job
      operationId: modifyJobWithId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateJobRequest'
    delete:
      tags:
      - Jobs
      summary: Delete Job
      operationId: deleteJobWithId
      responses:
        '204':
          description: No Content
  /jobs/{id}/job-applications:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      tags:
      - Jobs
      summary: List Applications For Job
      operationId: viewApplicationsForJob
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/JobApplication'
    post:
      tags:
      - Jobs
      summary: Create Job Application
      operationId: createJobApplication
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplication'
      requestBody:
        content:
          application/json:
            schema:
              type: object
  /users/{id}/jobs:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      tags:
      - Users
      summary: List Jobs For User
      operationId: listJobsForUser
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Job'
  /users/{id}/job-applications:
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      tags:
      - Users
      summary: List Applications For User
      operationId: viewApplicationsForUser
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/JobApplication'
  /job-applications/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      tags:
      - Jobs
      summary: Modify Job Application
      operationId: modifyJobApplicationWithId
      requestBody:
        description: Update the application details
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum:
                    - PENDING
                    - COMPLETE
                    - CANCELLED
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplication'
  /sessions:
    post:
      tags:
      - Users
      summary: Start Session (Login)
      operationId: startSession
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      security: []
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        password:
          type: string
        full_name:
          type: string
        roles:
          type: array
          items:
            type: string
    CreateUserRequest:
      type: object
      required:
        - email
        - password
        - full_name
        - roles
      properties:
        email:
          type: string
        password:
          type: string
        full_name:
          type: string
        roles:
          type: array
          items:
            type: string
    PutUserRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        full_name:
          type: string
        roles:
          type: array
          items:
            type: string
    Job:
      type: object
      properties:
        id:
          type: string
        creator_user_id:
          type: string
        start_time:
          type: string
        end_time:
          type: string
        activity:
          type: string
        dog:
          $ref: '#/components/schemas/Dog'
    PostJobRequest:
      type: object
      required:
        - start_time
        - end_time
        - activity
        - dog
      properties:
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        activity:
          type: string
        dog:
          $ref: '#/components/schemas/Dog'
    UpdateJobRequest:
      type: object
      required:
        - start_time
        - end_time
        - activity
        - dog
      properties:
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        activity:
          type: string
        dog:
          $ref: '#/components/schemas/Dog'
    Dog:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
        breed:
          type: string
        size:
          type: string
    JobApplication:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        user_id:
          type: string
        job_id:
          type: string
    Session:
      type: object
      properties:
        user_id:
          type: string
        auth_header:
          type: string
  securitySchemes:
    SessionToken:
      type: apiKey
      in: header
      name: Authorization
security:
  - SessionToken: []
